
twilio:
  send-grid:
    api-key: ${SENDGRID_KEY}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'

email: 'rits@weeryan17.com'
